#include "absim.hpp

int_vector_info_t const INT_VECTOR_INFO[] =
{
    { nullptr, nullptr },
    { "INT0", "External Interrupt Request 0" },
    { "INT1", "External Interrupt Request 1" },
    { "INT2", "External Interrupt Request 2" },
    { "INT3", "External Interrupt Request 3" },
    { nullptr, nullptr },
    { nullptr, nullptr },
    { "INT6", "External Interrupt Request 6" },
    { nullptr, nullptr },
    { "PCINT0", "Pin Change Interrupt Request 0" },
    { "USB_GEN", "USB General Interrupt Request" },
    { "USB_COM", "USB Endpoint/Pipe Interrupt Communication Request" },
    { "WDT", "Watchdog Time-out Interrupt" },
    { nullptr, nullptr },
    { nullptr, nullptr },
    { nullptr, nullptr },
    { "TIMER1_CAPT", "Timer/Counter1 Capture Event" },
    { "TIMER1_COMPA", "Timer/Counter1 Compare Match A" },
    { "TIMER1_COMPB", "Timer/Counter1 Compare Match B" },
    { "TIMER1_COMPC", "Timer/Counter1 Compare Match C" },
    { "TIMER1_OVF", "Timer/Counter1 Overflow" },
    { "TIMER0_COMPA", "Timer/Counter0 Compare Match A" },
    { "TIMER0_COMPB", "Timer/Counter0 Compare Match B" },
    { "TIMER0_OVF", "Timer/Counter0 Overflow" },
    { "SPI_STC", "SPI Serial Transfer Complete" },
    { "USART1_RX", "USART1, Rx Complete" },
    { "USART1_UDRE", "USART1 Data register Empty" },
    { "USART1_TX", "USART1, Tx Complete" },
    { "ANALOG_COMP", "Analog Comparator" },
    { "ADC", "ADC Conversion Complete" },
    { "EE_READY", "EEPROM Ready" },
    { "TIMER3_CAPT", "Timer/Counter3 Capture Event" },
    { "TIMER3_COMPA", "Timer/Counter3 Compare Match A" },
    { "TIMER3_COMPB", "Timer/Counter3 Compare Match B" },
    { "TIMER3_COMPC", "Timer/Counter3 Compare Match C" },
    { "TIMER3_OVF", "Timer/Counter3 Overflow" },
    { "TWI", "2-wire Serial Interface        " },
    { "SPM_READY", "Store Program Memory Read" },
    { "TIMER4_COMPA", "Timer/Counter4 Compare Match A" },
    { "TIMER4_COMPB", "Timer/Counter4 Compare Match B" },
    { "TIMER4_COMPD", "Timer/Counter4 Compare Match D" },
    { "TIMER4_OVF", "Timer/Counter4 Overflow" },
    { "TIMER4_FPF", "Timer/Counter4 Fault Protection Interrupt" },
};

reg_info_t const REG_INFO[] =
{
    { "r0", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r1", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r2", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r3", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r4", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r5", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r6", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r7", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r8", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r9", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r10", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r11", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r12", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r13", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r14", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r15", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r16", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r17", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r18", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r19", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r20", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r21", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r22", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r23", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r24", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r25", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r26", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r27", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r28", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r29", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r30", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "r31", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "PINB", { "PINB0", "PINB1", "PINB2", "PINB3", "PINB4", "PINB5", "PINB6", "PINB7", }, },
    { "DDRB", { "DDB0", "DDB1", "DDB2", "DDB3", "DDB4", "DDB5", "DDB6", "DDB7", }, },
    { "PORTB", { "PORTB0", "PORTB1", "PORTB2", "PORTB3", "PORTB4", "PORTB5", "PORTB6", "PORTB7", }, },
    { "PINC", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "PINC6", "PINC7", }, },
    { "DDRC", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "DDC6", "DDC7", }, },
    { "PORTC", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, "PORTC6", "PORTC7", }, },
    { "PIND", { "PIND0", "PIND1", "PIND2", "PIND3", "PIND4", "PIND5", "PIND6", "PIND7", }, },
    { "DDRD", { "DDD0", "DDD1", "DDD2", "DDD3", "DDD4", "DDD5", "DDD6", "DDD7", }, },
    { "PORTD", { "PORTD0", "PORTD1", "PORTD2", "PORTD3", "PORTD4", "PORTD5", "PORTD6", "PORTD7", }, },
    { "PINE", { nullptr, nullptr, "PINE2", nullptr, nullptr, nullptr, "PINE6", nullptr, }, },
    { "DDRE", { nullptr, nullptr, "DDE2", nullptr, nullptr, nullptr, "DDE6", nullptr, }, },
    { "PORTE", { nullptr, nullptr, "PORTE2", nullptr, nullptr, nullptr, "PORTE6", nullptr, }, },
    { "PINF", { "PINF0", "PINF1", nullptr, nullptr, "PINF4", "PINF5", "PINF6", "PINF7", }, },
    { "DDRF", { "DDF0", "DDF1", nullptr, nullptr, "DDF4", "DDF5", "DDF6", "DDF7", }, },
    { "PORTF", { "PORTF0", "PORTF1", nullptr, nullptr, "PORTF4", "PORTF5", "PORTF6", "PORTF7", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TIFR0", { "TOV0", "OCF0A", "OCF0B", nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TIFR1", { "TOV1", "OCF1A", "OCF1B", "OCF1C", nullptr, "ICF1", nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TIFR3", { "TOV3", "OCF3A", "OCF3B", "OCF3C", nullptr, "ICF3", nullptr, nullptr, }, },
    { "TIFR4", { nullptr, nullptr, "TOV4", nullptr, nullptr, "OCF4B", "OCF4A", "OCF4D", }, },
    { "TIFR5", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "PCIFR", { "PCIF0", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "EIFR", { "INTF0", "INTF1", "INTF2", "INTF3", "INTF4", "INTF5", "INTF6", "INTF7", }, },
    { "EIMSK", { "INT0", "INT1", "INT2", "INT3", "INT4", "INT5", "INT6", "INT7", }, },
    { "GPIOR0", { "GPIOR00", "GPIOR01", "GPIOR02", "GPIOR03", "GPIOR04", "GPIOR05", "GPIOR06", "GPIOR07", }, },
    { "EECR", { "EERE", "EEPE", "EEMPE", "EERIE", "EEPM0", "EEPM1", nullptr, nullptr, }, },
    { "EEDR", { "EEDR0", "EEDR1", "EEDR2", "EEDR3", "EEDR4", "EEDR5", "EEDR6", "EEDR7", }, },
    { "EEARL", { "EEAR0", "EEAR1", "EEAR2", "EEAR3", "EEAR4", "EEAR5", "EEAR6", "EEAR7", }, },
    { "EEARH", { "EEAR8", "EEAR9", "EEAR10", "EEAR11", nullptr, nullptr, nullptr, nullptr, }, },
    { "GTCCR", { "PSRSYNC", "PSRASY", nullptr, nullptr, nullptr, nullptr, nullptr, "TSM", }, },
    { "TCCR0A", { "WGM00", "WGM01", nullptr, nullptr, "COM0B0", "COM0B1", "COM0A0", "COM0A1", }, },
    { "TCCR0B", { "CS00", "CS01", "CS02", "WGM02", nullptr, nullptr, "FOC0B", "FOC0A", }, },
    { "TCNT0", { "TCNT0_0", "TCNT0_1", "TCNT0_2", "TCNT0_3", "TCNT0_4", "TCNT0_5", "TCNT0_6", "TCNT0_7", }, },
    { "OCR0A", { "OCR0A_0", "OCR0A_1", "OCR0A_2", "OCR0A_3", "OCR0A_4", "OCR0A_5", "OCR0A_6", "OCR0A_7", }, },
    { "OCR0B", { "OCR0B_0", "OCR0B_1", "OCR0B_2", "OCR0B_3", "OCR0B_4", "OCR0B_5", "OCR0B_6", "OCR0B_7", }, },
    { "PLLCSR", { "PLOCK", "PLLE", nullptr, nullptr, "PINDIV", nullptr, nullptr, nullptr, }, },
    { "GPIOR1", { "GPIOR10", "GPIOR11", "GPIOR12", "GPIOR13", "GPIOR14", "GPIOR15", "GPIOR16", "GPIOR17", }, },
    { "GPIOR2", { "GPIOR20", "GPIOR21", "GPIOR22", "GPIOR23", "GPIOR24", "GPIOR25", "GPIOR26", "GPIOR27", }, },
    { "SPCR", { "SPR0", "SPR1", "CPHA", "CPOL", "MSTR", "DORD", "SPE", "SPIE", }, },
    { "SPSR", { "SPI2X", nullptr, nullptr, nullptr, nullptr, nullptr, "WCOL", "SPIF", }, },
    { "SPDR", { "SPDR0", "SPDR1", "SPDR2", "SPDR3", "SPDR4", "SPDR5", "SPDR6", "SPDR7", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "ACSR", { "ACIS0", "ACIS1", "ACIC", "ACIE", "ACI", "ACO", "ACBG", "ACD", }, },
    { "OCDR", { "OCDR0", "OCDR1", "OCDR2", "OCDR3", "OCDR4", "OCDR5", "OCDR6", "OCDR7", }, },
    { "PLLFRQ", { "PDIV0", "PDIV1", "PDIV2", "PDIV3", "PLLTM0", "PLLTM1", "PLLUSB", "PINMUX", }, },
    { "SMCR", { "SE", "SM0", "SM1", "SM2", nullptr, nullptr, nullptr, nullptr, }, },
    { "MCUSR", { "PORF", "EXTRF", "BORF", "WDRF", "JTRF", nullptr, nullptr, nullptr, }, },
    { "MCUCR", { "IVCE", "IVSEL", nullptr, nullptr, "PUD", nullptr, nullptr, "JTD", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "SPMCSR", { "SPMEN", "PGERS", "PGWRT", "BLBSET", "RWWSRE", "SIGRD", "RWWSB", "SPMIE", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "RAMPZ", { "RAMPZ0", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "EIND", { "EIND0", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "WDTCSR", { "WDP0", "WDP1", "WDP2", "WDE", "WDCE", "WDP3", "WDIE", "WDIF", }, },
    { "CLKPR", { "CLKPS0", "CLKPS1", "CLKPS2", "CLKPS3", nullptr, nullptr, nullptr, "CLKPCE", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "PRR0", { "PRADC", "PRUSART0", "PRSPI", "PRTIM1", nullptr, "PRTIM0", "PRTIM2", "PRTWI", }, },
    { "PRR1", { "PRUSART1", nullptr, nullptr, "PRTIM3", nullptr, nullptr, nullptr, "PRUSB", }, },
    { "OSCCAL", { "CAL0", "CAL1", "CAL2", "CAL3", "CAL4", "CAL5", "CAL6", "CAL7", }, },
    { "RCCTRL", { "RCFREQ", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "PCICR", { "PCIE0", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "EICRA", { "ISC00", "ISC01", "ISC10", "ISC11", "ISC20", "ISC21", "ISC30", "ISC31", }, },
    { "EICRB", { "ISC40", "ISC41", "ISC50", "ISC51", "ISC60", "ISC61", "ISC70", "ISC71", }, },
    { "PCMSK0", { "PCINT0", "PCINT1", "PCINT2", "PCINT3", "PCINT4", "PCINT5", "PCINT6", "PCINT7", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TIMSK0", { "TOIE0", "OCIE0A", "OCIE0B", nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TIMSK1", { "TOIE1", "OCIE1A", "OCIE1B", "OCIE1C", nullptr, "ICIE1", nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TIMSK3", { "TOIE3", "OCIE3A", "OCIE3B", "OCIE3C", nullptr, "ICIE3", nullptr, nullptr, }, },
    { "TIMSK4", { nullptr, nullptr, "TOIE4", nullptr, nullptr, "OCIE4B", "OCIE4A", "OCIE4D", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "ADCL", { "ADCL0", "ADCL1", "ADCL2", "ADCL3", "ADCL4", "ADCL5", "ADCL6", "ADCL7", }, },
    { "ADCH", { "ADCH0", "ADCH1", "ADCH2", "ADCH3", "ADCH4", "ADCH5", "ADCH6", "ADCH7", }, },
    { "ADCSRA", { "ADPS0", "ADPS1", "ADPS2", "ADIE", "ADIF", "ADATE", "ADSC", "ADEN", }, },
    { "ADCSRB", { "ADTS0", "ADTS1", "ADTS2", "ADTS3", nullptr, "MUX5", "ACME", "ADHSM", }, },
    { "ADMUX", { "MUX0", "MUX1", "MUX2", "MUX3", "MUX4", "ADLAR", "REFS0", "REFS1", }, },
    { "DIDR2", { "ADC8D", "ADC9D", "ADC10D", "ADC11D", "ADC12D", "ADC13D", nullptr, nullptr, }, },
    { "DIDR0", { "ADC0D", "ADC1D", "ADC2D", "ADC3D", "ADC4D", "ADC5D", "ADC6D", "ADC7D", }, },
    { "DIDR1", { "AIN0D", "AIN1D", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TCCR1A", { "WGM10", "WGM11", "COM1C0", "COM1C1", "COM1B0", "COM1B1", "COM1A0", "COM1A1", }, },
    { "TCCR1B", { "CS10", "CS11", "CS12", "WGM12", "WGM13", nullptr, "ICES1", "ICNC1", }, },
    { "TCCR1C", { nullptr, nullptr, nullptr, nullptr, nullptr, "FOC1C", "FOC1B", "FOC1A", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TCNT1L", { "TCNT1L0", "TCNT1L1", "TCNT1L2", "TCNT1L3", "TCNT1L4", "TCNT1L5", "TCNT1L6", "TCNT1L7", }, },
    { "TCNT1H", { "TCNT1H0", "TCNT1H1", "TCNT1H2", "TCNT1H3", "TCNT1H4", "TCNT1H5", "TCNT1H6", "TCNT1H7", }, },
    { "ICR1L", { "ICR1L0", "ICR1L1", "ICR1L2", "ICR1L3", "ICR1L4", "ICR1L5", "ICR1L6", "ICR1L7", }, },
    { "ICR1H", { "ICR1H0", "ICR1H1", "ICR1H2", "ICR1H3", "ICR1H4", "ICR1H5", "ICR1H6", "ICR1H7", }, },
    { "OCR1AL", { "OCR1AL0", "OCR1AL1", "OCR1AL2", "OCR1AL3", "OCR1AL4", "OCR1AL5", "OCR1AL6", "OCR1AL7", }, },
    { "OCR1AH", { "OCR1AH0", "OCR1AH1", "OCR1AH2", "OCR1AH3", "OCR1AH4", "OCR1AH5", "OCR1AH6", "OCR1AH7", }, },
    { "OCR1BL", { "OCR1BL0", "OCR1BL1", "OCR1BL2", "OCR1BL3", "OCR1BL4", "OCR1BL5", "OCR1BL6", "OCR1BL7", }, },
    { "OCR1BH", { "OCR1BH0", "OCR1BH1", "OCR1BH2", "OCR1BH3", "OCR1BH4", "OCR1BH5", "OCR1BH6", "OCR1BH7", }, },
    { "OCR1CL", { "OCR1CL0", "OCR1CL1", "OCR1CL2", "OCR1CL3", "OCR1CL4", "OCR1CL5", "OCR1CL6", "OCR1CL7", }, },
    { "OCR1CH", { "OCR1CH0", "OCR1CH1", "OCR1CH2", "OCR1CH3", "OCR1CH4", "OCR1CH5", "OCR1CH6", "OCR1CH7", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TCCR3A", { "WGM30", "WGM31", "COM3C0", "COM3C1", "COM3B0", "COM3B1", "COM3A0", "COM3A1", }, },
    { "TCCR3B", { "CS30", "CS31", "CS32", "WGM32", "WGM33", nullptr, "ICES3", "ICNC3", }, },
    { "TCCR3C", { nullptr, nullptr, nullptr, nullptr, nullptr, "FOC3C", "FOC3B", "FOC3A", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TCNT3L", { "TCNT3L0", "TCNT3L1", "TCNT3L2", "TCNT3L3", "TCNT3L4", "TCNT3L5", "TCNT3L6", "TCNT3L7", }, },
    { "TCNT3H", { "TCNT3H0", "TCNT3H1", "TCNT3H2", "TCNT3H3", "TCNT3H4", "TCNT3H5", "TCNT3H6", "TCNT3H7", }, },
    { "ICR3L", { "ICR3L0", "ICR3L1", "ICR3L2", "ICR3L3", "ICR3L4", "ICR3L5", "ICR3L6", "ICR3L7", }, },
    { "ICR3H", { "ICR3H0", "ICR3H1", "ICR3H2", "ICR3H3", "ICR3H4", "ICR3H5", "ICR3H6", "ICR3H7", }, },
    { "OCR3AL", { "OCR3AL0", "OCR3AL1", "OCR3AL2", "OCR3AL3", "OCR3AL4", "OCR3AL5", "OCR3AL6", "OCR3AL7", }, },
    { "OCR3AH", { "OCR3AH0", "OCR3AH1", "OCR3AH2", "OCR3AH3", "OCR3AH4", "OCR3AH5", "OCR3AH6", "OCR3AH7", }, },
    { "OCR3BL", { "OCR3BL0", "OCR3BL1", "OCR3BL2", "OCR3BL3", "OCR3BL4", "OCR3BL5", "OCR3BL6", "OCR3BL7", }, },
    { "OCR3BH", { "OCR3BH0", "OCR3BH1", "OCR3BH2", "OCR3BH3", "OCR3BH4", "OCR3BH5", "OCR3BH6", "OCR3BH7", }, },
    { "OCR3CL", { "OCR3CL0", "OCR3CL1", "OCR3CL2", "OCR3CL3", "OCR3CL4", "OCR3CL5", "OCR3CL6", "OCR3CL7", }, },
    { "OCR3CH", { "OCR3CH0", "OCR3CH1", "OCR3CH2", "OCR3CH3", "OCR3CH4", "OCR3CH5", "OCR3CH6", "OCR3CH7", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TWBR", { "TWBR0", "TWBR1", "TWBR2", "TWBR3", "TWBR4", "TWBR5", "TWBR6", "TWBR7", }, },
    { "TWSR", { "TWPS0", "TWPS1", nullptr, "TWS3", "TWS4", "TWS5", "TWS6", "TWS7", }, },
    { "TWAR", { "TWGCE", "TWA0", "TWA1", "TWA2", "TWA3", "TWA4", "TWA5", "TWA6", }, },
    { "TWDR", { "TWD0", "TWD1", "TWD2", "TWD3", "TWD4", "TWD5", "TWD6", "TWD7", }, },
    { "TWCR", { "TWIE", nullptr, "TWEN", "TWWC", "TWSTO", "TWSTA", "TWEA", "TWINT", }, },
    { "TWAMR", { nullptr, "TWAM0", "TWAM1", "TWAM2", "TWAM3", "TWAM4", "TWAM5", "TWAM6", }, },
    { "TCNT4L", { "TC40", "TC41", "TC42", "TC43", "TC44", "TC45", "TC46", "TC47", }, },
    { "TC4H", { "TC48", "TC49", "TC410", nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "TCCR4A", { "PWM4B", "PWM4A", "FOC4B", "FOC4A", "COM4B0", "COM4B1", "COM4A0", "COM4A1", }, },
    { "TCCR4B", { "CS40", "CS41", "CS42", "CS43", "DTPS40", "DTPS41", "PSR4", "PWM4X", }, },
    { "TCCR4C", { "PWM4D", "FOC4D", "COM4D0", "COM4D1", "COM4B0S", "COM4B1S", "COM4A0S", "COM4A1S", }, },
    { "TCCR4D", { "WGM40", "WGM41", "FPF4", "FPAC4", "FPES4", "FPNC4", "FPEN4", "FPIE4", }, },
    { "TCCR4E", { "OC4OE0", "OC4OE1", "OC4OE2", "OC4OE3", "OC4OE4", "OC4OE5", "ENHC4", "TLOCK4", }, },
    { "CLKSEL0", { "CLKS", nullptr, "EXTE", "RCE", "EXSUT0", "EXSUT1", "RCSUT0", "RCSUT1", }, },
    { "CLKSEL1", { "EXCKSEL0", "EXCKSEL1", "EXCKSEL2", "EXCKSEL3", "RCCKSEL0", "RCCKSEL1", "RCCKSEL2", "RCCKSEL3", }, },
    { "CLKSTA", { "EXTON", "RCON", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "UCSR1A", { "MPCM1", "U2X1", "UPE1", "DOR1", "FE1", "UDRE1", "TXC1", "RXC1", }, },
    { "UCSR1B", { "TXB81", "RXB81", "UCSZ12", "TXEN1", "RXEN1", "UDRIE1", "TXCIE1", "RXCIE1", }, },
    { "UCSR1C", { "UCPOL1", "UCSZ10", "UCSZ11", "USBS1", "UPM10", "UPM11", "UMSEL10", "UMSEL11", }, },
    { "UCSR1D", { "RTSEN", "CTSEN", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "UBRR1L", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "UBRR1H", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "UDR1", { "UDR1_0", "UDR1_1", "UDR1_2", "UDR1_3", "UDR1_4", "UDR1_5", "UDR1_6", "UDR1_7", }, },
    { "OCR4A", { "OCR4A0", "OCR4A1", "OCR4A2", "OCR4A3", "OCR4A4", "OCR4A5", "OCR4A6", "OCR4A7", }, },
    { "OCR4B", { "OCR4B0", "OCR4B1", "OCR4B2", "OCR4B3", "OCR4B4", "OCR4B5", "OCR4B6", "OCR4B7", }, },
    { "OCR4C", { "OCR4C0", "OCR4C1", "OCR4C2", "OCR4C3", "OCR4C4", "OCR4C5", "OCR4C6", "OCR4C7", }, },
    { "OCR4D", { "OCR4D0", "OCR4D1", "OCR4D2", "OCR4D3", "OCR4D4", "OCR4D5", "OCR4D6", "OCR4D7", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "DT4", { "DT4L0", "DT4L1", "DT4L2", "DT4L3", "OTGPADE", "DT4L5", "DT4L6", "DT4L7", }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "UDCON", { "DETACH", "RMWKUP", "LSM", "RSTCPU", nullptr, nullptr, nullptr, nullptr, }, },
    { "UDINT", { "SUSPI", nullptr, "SOFI", "EORSTI", "WAKEUPI", "EORSMI", "UPRSMI", nullptr, }, },
    { "UDIEN", { "SUSPE", nullptr, "SOFE", "EORSTE", "WAKEUPE", "EORSME", "UPRSME", nullptr, }, },
    { "UDADDR", { "UADD0", "UADD1", "UADD2", "UADD3", "UADD4", "UADD5", "UADD6", "ADDEN", }, },
    { "UDFNUML", { "FNUM0", "FNUM1", "FNUM2", "FNUM3", "FNUM4", "FNUM5", "FNUM6", "FNUM7", }, },
    { "UDFNUMH", { "FNUM8", "FNUM9", "FNUM10", nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "UDMFN", { nullptr, nullptr, nullptr, nullptr, "FNCERR", nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "UEINTX", { "TXINI", "STALLEDI", "RXOUTI", "RXSTPI", "NAKOUTI", "RWAL", "NAKINI", "FIFOCON", }, },
    { "UENUM", { "UENUM_0", "UENUM_1", "UENUM_2", nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "UERST", { "EPRST0", "EPRST1", "EPRST2", "EPRST3", "EPRST4", "EPRST5", "EPRST6", nullptr, }, },
    { "UECONX", { "EPEN", nullptr, nullptr, "RSTDT", "STALLRQC", "STALLRQ", nullptr, nullptr, }, },
    { "UECFG0X", { "EPDIR", nullptr, nullptr, nullptr, nullptr, nullptr, "EPTYPE0", "EPTYPE1", }, },
    { "UECFG1X", { nullptr, "ALLOC", "EPBK0", "EPBK1", "EPSIZE0", "EPSIZE1", "EPSIZE2", nullptr, }, },
    { "UESTA0X", { "NBUSYBK0", "NBUSYBK1", "DTSEQ0", "DTSEQ1", nullptr, "UNDERFI", "OVERFI", "CFGOK", }, },
    { "UESTA1X", { "CURRBK0", "CURRBK1", "CTRLDIR", nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "UEIENX", { "TXINE", "STALLEDE", "RXOUTE", "RXSTPE", "NAKOUTE", nullptr, "NAKINE", "FLERRE", }, },
    { "UEDATX", { "DAT0", "DAT1", "DAT2", "DAT3", "DAT4", "DAT5", "DAT6", "DAT7", }, },
    { "UEBCLX", { "BYCT0", "BYCT1", "BYCT2", "BYCT3", "BYCT4", "BYCT5", "BYCT6", "BYCT7", }, },
    { "UEBCHX", { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { "UEINT", { "EPINT0", "EPINT1", "EPINT2", "EPINT3", "EPINT4", "EPINT5", "EPINT6", nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
    { nullptr, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, }, },
};
